TavridaTestTask/Models/CompaniesBranch.cs
using System;
using System.Collections.Generic;

namespace TavridaTestTask.Models;

public partial class CompaniesBranch
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public int CompanyId { get; set; }

    public virtual Company Company { get; set; } = null!;
}

TavridaTestTask/Models/Company.cs
namespace TavridaTestTask.Models;

public partial class Company
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public bool BinarySign { get; set; }

    public virtual ICollection<CompaniesBranch> CompaniesBranches { get; } = new List<CompaniesBranch>();
}

TavridaTestTask/Models/Data/TestTaskContext.cs
using Microsoft.EntityFrameworkCore;

namespace TavridaTestTask.Models;

public partial class TestTaskContext : DbContext
{
    public TestTaskContext(DbContextOptions<TestTaskContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CompaniesBranch> CompaniesBranches { get; set; }

    public virtual DbSet<Company> Companies { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer("Name=ConnectionStrings:DefaultConnection");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CompaniesBranch>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Companie__3214EC07FBE617E4");

            entity.Property(e => e.Name)
                .HasMaxLength(150)
                .IsUnicode(false);

            entity.HasOne(d => d.Company).WithMany(p => p.CompaniesBranches)
                .HasForeignKey(d => d.CompanyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Companies__Compa__267ABA7A");
        });

        modelBuilder.Entity<Company>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Companie__3214EC07D292AB74");

            entity.Property(e => e.Name)
                .HasMaxLength(150)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

TavridaTestTask/Models/ViewModels/CompanyBranchViewModel.cs
using System.ComponentModel;

namespace TavridaTestTask.Models.ViewModels
{
    public class CompanyBranchViewModel
    {
        [DisplayName("Филиал")]
        public string CompanyBranchName { get; set; } = string.Empty;
        [DisplayName("Компания Филиала")]
        public string CompanyName { get; set; } = string.Empty;
        [DisplayName("Группа Компании")]
        public bool CompanyGroup { get; set; }
        [DisplayName("Связанные филиалы")]
        public string RelatedBranches { get; set; } = string.Empty;
    }
}

TavridaTestTask/Models/ViewModels/ErrorViewModel.cs
namespace TavridaTestTask.Models.ViewModels
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TavridaTestTask/Controllers/CompaniesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using System.Text;
using TavridaTestTask.Models;
using TavridaTestTask.Models.ViewModels;

namespace TavridaTestTask.Controllers
{
    public class CompaniesController : Controller
    {
        private readonly ILogger<CompaniesController> _logger;
        private readonly TestTaskContext _context;

        public CompaniesController(ILogger<CompaniesController> logger, TestTaskContext context)
        {
            _logger = logger;
            _context = context;
        }

        public async Task<IActionResult> CompanyBranches()
        {
            var CompaniesBranches = from cb in _context.CompaniesBranches
                                    select new CompanyBranchViewModel()
                                    {
                                        CompanyBranchName = cb.Name,
                                        CompanyName = cb.Company.Name,
                                        CompanyGroup = cb.Company.BinarySign,
                                        RelatedBranches = !cb.Company.BinarySign ?
                                            new StringBuilder().AppendJoin(", ", cb.Company.CompaniesBranches.Select(x => x.Name.ToString())).ToString():
                                            string.Join(", ", _context.CompaniesBranches.Select(x => x.Name))
                                    };
            return CompaniesBranches != null ?
                          View(await CompaniesBranches.ToListAsync()) :
                          Problem("Entity set 'CompaniesBranches'  is null.");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TavridaTestTask/Views/Companies/CompanyBranches.cshtml
@model IEnumerable<TavridaTestTask.Models.ViewModels.CompanyBranchViewModel>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Филиалы Компаний</title>
</head>
<body>
    <h1>Филиалы Компаний</h1>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.CompanyBranchName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CompanyName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CompanyGroup)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RelatedBranches)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.CompanyBranchName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CompanyName)
                    </td>
                    <td>
                        @{ 
                            var group = item.CompanyGroup ? 2 : 1;
                        }
                        @(group)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RelatedBranches)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</body>
</html>

TavridaTestTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TavridaTestTask</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TavridaTestTask.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Companies" asp-action="CompanyBranches">Тестовое задание Таврида Электрик</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            Тестовое задание Таврида Электрик
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>